### PR TITLE
Trim firmware string. Closes #299.

### LINKED ISSUE #299: Random chars at the end of firmware string
### Commit
db438915d632097fc1c29a9ebaefad27370f396b

### Steps to reproduce
Launch robot with real system

### Expected behavior
Firmware of each joint is displayed properly

### Observed behavior
Random chars are added to the firmware string

### Logfiles
```
[ INFO] [1578999408.520278926]: Firmware version [prbt_joint_1]: 100 Build:11158 Date:2018-06-07 16:49:55
[ INFO] [1578999408.520434190]: Firmware version [prbt_joint_2]: 100 Build:11158 Date:2018-06-07 16:49:55
[ INFO] [1578999408.520502982]: Firmware version [prbt_joint_3]: 100 Build:11158 Date:2018-06-07 16:49:55u
[ INFO] [1578999408.520559978]: Firmware version [prbt_joint_4]: 100 Build:11158 Date:2018-06-07 16:49:555
[ INFO] [1578999408.520618411]: Firmware version [prbt_joint_5]: 100 Build:11158 Date:2018-06-07 16:49:55E
[ INFO] [1578999408.520675839]: Firmware version [prbt_joint_6]: 100 Build:11158 Date:2018-06-07 16:49:55
```

Result of command below see [candump.log](https://github.com/PilzDE/pilz_robots/files/4058800/candump.log)
```
rosservice call /prbt/driver/get_object "node: 'prbt_joint_1'
object: '100A'
cached: false" 
success: True
message: ''
value: "100 Build:11158 Date:2018-06-07 16:49:55%"
```

### PR DESCRIPTION
**Pull request by agutenkunst**

### CODE REVIEW

**Review by ct2034 — COMMENTED** [review]
Please add a comment, mentioning the CAN string size. Otherwise this is a bit of a magic number

**Review by ct2034 — CHANGES_REQUESTED** [review]
Please add a comment, mentioning the CAN string size. Otherwise this is a bit of a magic number

File: prbt_hardware_support/src/system_info.cpp [hunk 1]
```diff
@@ -34,6 +34,8 @@ static const std::string JOINT_STATE_TOPIC {"/joint_states"};
 
 static const std::string GET_FIRMWARE_VERION_OBJECT{"100A"};
 
+static const std::size_t FIRMWARE_STRING_LENGTH{40};
```
Comment (ct2034) [inline prbt_hardware_support/src/system_info.cpp]:
```suggestion
// Currently the string is defined to be 41 characters long, but the last character can be omitted.
static const std::size_t FIRMWARE_STRING_LENGTH{40}; 
```

**Review by ct2034 — COMMENTED** [review]
a suggestion @agutenkunst

**Review by ct2034 — APPROVED** [review]
