### PR TITLE
Fix/auto modbus register range

### LINKED ISSUE #154: ModbusReadClient does not take into account register range from api spec
Ansatz:

Determine minimal modbus register range from api spec on parameter server.

### PR DESCRIPTION
**Pull request by martiniil**
Fixes #154

### CODE REVIEW

**Comment by martiniil** [comment]
I can not get rid of this gap in function coverage:

> prbt_hardware_support::ModbusApiSpecTemplated<ros::NodeHandle>::getMinMaxRegisterDefintion() const::{lambda(std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned int> const&, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned int> const&)#1}::_FUN(std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned int> const&, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned int> const&)

What I know is that it is a static invoke function that is generated from the lambda expression in `getMinMaxRegisterDefintion()`. I assume this is a general issue when using lambdas.

**Comment by jschleicher** [comment]
What gcc version are you using? In 8.3.0 the following patch was applied, that may fix this problem (if that is the case, it is not your fault for sure and you can ignore the line):
https://patchwork.ozlabs.org/patch/968991/
https://github.com/gcc-mirror/gcc/commit/7de708f8f52a6e674eeb9ba729df2682bae34aea#diff-e4f19c81816dc138788262149d2fa68f

**Comment by martiniil** [comment]
@jschleicher Thank you! I can confirm that the problem is fixed using gcc 8.3.0 and lcov 1.14

File: prbt_hardware_support/src/pilz_modbus_read_client_node.cpp [hunk 1]
```diff
@@ -39,42 +41,71 @@ int main(int argc, char **argv)
 {
   ros::init(argc, argv, "modbus_read_node");
 
-  ros::NodeHandle nh {"~"};
+  ros::NodeHandle pnh{"~"};
+  ros::NodeHandle nh;
+
+  bool has_register_range_parameters = pnh.hasParam(PARAM_NUM_REGISTERS_TO_READ_STR) &&
```
Comment (agutenkunst) [inline prbt_hardware_support/src/pilz_modbus_read_client_node.cpp]: Seems to me that you could condense all parts handling this into one section rather than distributing it all over the file

File: prbt_hardware_support/src/pilz_modbus_read_client_node.cpp [hunk 2]
```diff
@@ -39,42 +41,71 @@ int main(int argc, char **argv)
...
-  nh.param<std::string>(PARAM_MODBUS_TOPIC_NAME_STR, modbus_topic_name,
-                        TOPIC_MODBUS_READ);
-
+  pnh.param<std::string>(PARAM_MODBUS_TOPIC_NAME_STR, modbus_topic_name,
+                         TOPIC_MODBUS_READ);
 
   // LCOV_EXCL_STOP
 
-  prbt_hardware_support::PilzModbusReadClient modbus_client(nh,
+  if (!has_register_range_parameters)
```
Comment (agutenkunst) [inline prbt_hardware_support/src/pilz_modbus_read_client_node.cpp]: See comment above

File: prbt_hardware_support/include/prbt_hardware_support/modbus_api_spec.h [hunk 3]
```diff
@@ -116,6 +118,20 @@ class ModbusApiSpecTemplated
     }
   }
 
+  inline std::pair<unsigned int, unsigned int> getMinMaxRegisterDefintion() const
```
Comment (agutenkunst) [inline prbt_hardware_support/include/prbt_hardware_support/modbus_api_spec.h]: I would like to say that a comment is missing but somehow I feel that it rather a missing concept of something like "range". Maybe a dedicated class for more expressiveness?

Comment (agutenkunst) [reply prbt_hardware_support/include/prbt_hardware_support/modbus_api_spec.h]: Or... just provide a getMinRegister() and a getMaxRegister() to KISS

**Review by agutenkunst — CHANGES_REQUESTED** [review]

File: prbt_hardware_support/include/prbt_hardware_support/modbus_api_spec.h (hunk 3 above)
Comment (agutenkunst) [reply prbt_hardware_support/include/prbt_hardware_support/modbus_api_spec.h]: Why not just getMinRegister() does "Definition" provide any more useful information?

Comment (martiniil) [reply prbt_hardware_support/include/prbt_hardware_support/modbus_api_spec.h]: It is consistent with the other methods: `setRegisterDefinition()` and so on.

Comment (martiniil) [reply prbt_hardware_support/include/prbt_hardware_support/modbus_api_spec.h]: Did you choose it, because "setRegister()" would have been misleading?

Comment (agutenkunst) [reply prbt_hardware_support/include/prbt_hardware_support/modbus_api_spec.h]: Yep. But also not ideal

**Review by agutenkunst — APPROVED** [review]
