### PR TITLE
Inc. port of unittest_libmodbus_client testcases

### LINKED ISSUE #193: unittest_libmodbus_client has timeout in buildfarm
Job fails on Buildserver due to timeout in test https://github.com/PilzDE/pilz_robots/blob/02bfdde504aa3357a48412b8da4b3d41408b5411/prbt_hardware_support/test/unittests/unittest_libmodbus_client.cpp#L210
http://build.ros.org/job/Mdev__pilz_robots__ubuntu_bionic_amd64/38/console

### Commit
54d7b927a5cfa72f1e587100f8d5b82435d4ff23

### Steps to reproduce
unclear

### Expected behavior
Test should not timeout

### Observed behavior
The does timeout

### Logfiles
https://github.com/PilzDE/pilz_robots/blob/02bfdde504aa3357a48412b8da4b3d41408b5411/prbt_hardware_support/test/unittests/unittest_libmodbus_client.cpp#L210
http://build.ros.org/job/Mdev__pilz_robots__ubuntu_bionic_amd64/38/console

### Possible solution
One thing that could help stabilizing these tests a bit would be to assign a different Port on every TestCase. I will open a PR on this.

### PR DESCRIPTION
**Pull request by agutenkunst**
* Tests are unstable and still get stuck. Maybe this will help.
* Hopefully closes #193

### CODE REVIEW

File: prbt_hardware_support/test/unittests/unittest_libmodbus_client.cpp [hunk 1]
```diff
@@ -34,16 +34,27 @@ namespace pilz_modbus_client_test
...
 
+class LibModbusClientTest : public testing::Test
+{
+public:
+  void TearDown();
+};
+
+void LibModbusClientTest::TearDown()
+{
+  active_port++;
```
Comment (ct2034) [inline prbt_hardware_support/test/unittests/unittest_libmodbus_client.cpp]: I would suggest limiting the range of ports somehow. Otherwise, this thing has the potential to take over all your ports over time :wink:

**Review by ct2034 — DISMISSED** [review]

**Review by martiniil — APPROVED** [review]
